package com.stingers.alttpr.model

import alttpr.shared.generated.resources.Res
import alttpr.shared.generated.resources.gamemode_all_dungeons_boots
import alttpr.shared.generated.resources.gamemode_all_dungeons_keysanity_boots
import alttpr.shared.generated.resources.gamemode_ambrosia
import alttpr.shared.generated.resources.gamemode_beginner
import alttpr.shared.generated.resources.gamemode_black_friday_hell_seed
import alttpr.shared.generated.resources.gamemode_blitzmode
import alttpr.shared.generated.resources.gamemode_bot_testing
import alttpr.shared.generated.resources.gamemode_casual_all_dungeons_boots
import alttpr.shared.generated.resources.gamemode_casual_boots
import alttpr.shared.generated.resources.gamemode_casual_boots_fast
import alttpr.shared.generated.resources.gamemode_crosskeys
import alttpr.shared.generated.resources.gamemode_custom
import alttpr.shared.generated.resources.gamemode_default
import alttpr.shared.generated.resources.gamemode_eight_piece_hunt
import alttpr.shared.generated.resources.gamemode_enemizer_boots
import alttpr.shared.generated.resources.gamemode_fadkeys
import alttpr.shared.generated.resources.gamemode_fadkeys_gt
import alttpr.shared.generated.resources.gamemode_goldrush
import alttpr.shared.generated.resources.gamemode_goldrush_keysanity
import alttpr.shared.generated.resources.gamemode_inverted_vanilla
import alttpr.shared.generated.resources.gamemode_invrosia
import alttpr.shared.generated.resources.gamemode_invrosia_boots
import alttpr.shared.generated.resources.gamemode_ladder_s12_open_pseudoboots
import alttpr.shared.generated.resources.gamemode_ladder_s7_potpourri
import alttpr.shared.generated.resources.gamemode_lightspeed
import alttpr.shared.generated.resources.gamemode_nightmare
import alttpr.shared.generated.resources.gamemode_open_boots
import alttpr.shared.generated.resources.gamemode_open_boots_fast
import alttpr.shared.generated.resources.gamemode_open_boots_mc
import alttpr.shared.generated.resources.gamemode_open_flute
import alttpr.shared.generated.resources.gamemode_owg
import alttpr.shared.generated.resources.gamemode_saku_league_boots
import alttpr.shared.generated.resources.gamemode_sgl_germany_open
import alttpr.shared.generated.resources.gamemode_speedgaming_live_2021
import alttpr.shared.generated.resources.gamemode_speedgaming_live_2022
import alttpr.shared.generated.resources.gamemode_speedgaming_live_2023
import alttpr.shared.generated.resources.gamemode_speedgaming_live_2024
import alttpr.shared.generated.resources.gamemode_standard_boots
import alttpr.shared.generated.resources.gamemode_super_quick
import alttpr.shared.generated.resources.gamemode_tournament_all_dungeons_keysanity_boots
import alttpr.shared.generated.resources.gamemode_tournament_hard_item_pool
import alttpr.shared.generated.resources.gamemode_tournament_inverted_keysanity
import alttpr.shared.generated.resources.gamemode_tournament_keysanity
import alttpr.shared.generated.resources.gamemode_tournament_mc_bossmizer
import alttpr.shared.generated.resources.gamemode_triforce_hunt_30
import alttpr.shared.generated.resources.gamemode_triforce_hunt_40
import alttpr.shared.generated.resources.gamemode_wtfrosia
import com.stingers.alttpr.model.api.Accessibility
import com.stingers.alttpr.model.api.BossShuffle
import com.stingers.alttpr.model.api.Crystals
import com.stingers.alttpr.model.api.EnemyDamage
import com.stingers.alttpr.model.api.EnemyHealth
import com.stingers.alttpr.model.api.EnemyShuffle
import com.stingers.alttpr.model.api.Entrances
import com.stingers.alttpr.model.api.Glitches
import com.stingers.alttpr.model.api.Goals
import com.stingers.alttpr.model.api.Item
import com.stingers.alttpr.model.api.ItemFunctionality
import com.stingers.alttpr.model.api.ItemLocation
import com.stingers.alttpr.model.api.ItemPlacement
import com.stingers.alttpr.model.api.ItemPool
import com.stingers.alttpr.model.api.Keysanity
import com.stingers.alttpr.model.api.Toggle
import com.stingers.alttpr.model.api.Weapons
import com.stingers.alttpr.model.api.WorldState
import org.jetbrains.compose.resources.StringResource

enum class GameMode(val title: StringResource, val api: AlttprApi) {
    DEFAULT(Res.string.gamemode_default, AlttprApi.RANDOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.On,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false
        )
    },
    BEGINNER(Res.string.gamemode_beginner, AlttprApi.RANDOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Basic,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Locations,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Standard,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Assured,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false
        )
    },
    OWG(Res.string.gamemode_owg, AlttprApi.RANDOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.Overworld,
            itemPlacement = ItemPlacement.Basic,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Locations,
            goal = Goals.FastGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.On,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false
        )
    },
    CROSSKEYS(Res.string.gamemode_crosskeys, AlttprApi.RANDOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Full,
            accessibility = Accessibility.Items,
            goal = Goals.FastGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.Crossed,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.On,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false
        )
    },
    SUPER_QUICK(Res.string.gamemode_super_quick, AlttprApi.RANDOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Basic,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Beatable,
            goal = Goals.FastGanon,
            towerCrystals = Crystals.Zero,
            ganonCrystals = Crystals.Zero,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Assured,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false
        )
    },
    NIGHTMARE(Res.string.gamemode_nightmare, AlttprApi.RANDOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Full,
            accessibility = Accessibility.Beatable,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Inverted,
            entrances = Entrances.Insanity,
            bossShuffle = BossShuffle.Random,
            enemyShuffle = EnemyShuffle.Random,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Swordless,
            itemPool = ItemPool.Expert,
            itemFunctionality = ItemFunctionality.Expert,
            enemyDamage = EnemyDamage.Random,
            enemyHealth = EnemyHealth.Expert,
            pseudoboots = false
        )
    },
    // --- Starting Equipment & QoL ---
    CASUAL_BOOTS(Res.string.gamemode_casual_boots, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Standard,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Assured,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            startingEquipment = setOf(Item.PegasusBoots),
            notes = "Casual w/ Boots Start",
        )
    },
    AMBROSIA(Res.string.gamemode_ambrosia, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Standard,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Assured,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            regionToggles = CustomRegionToggles(bossNormalLocation = false),
            bootsLocationSpoiler = true,
            notes = "This is a sword-assured standard seed (.casual) where the Uncle will spoil the Boots location at the start, and all dungeon bosses are guaranteed to drop an item (not a map/compass/key).",
        )
    },
    BLITZMODE(Res.string.gamemode_blitzmode, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.FastGanon,
            towerCrystals = Crystals.Four,
            ganonCrystals = Crystals.Four,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.On,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            // 2x ProgressiveSword/ProgressiveGlove in sahasrahbot's eq (Master Sword, Titan's
            // Mitts) can't be a Set duplicate, so grant the upgraded items directly instead.
            startingEquipment = setOf(
                Item.MasterSword, Item.TitansMitt, Item.MoonPearl, Item.Lamp,
                Item.PegasusBoots, Item.FluteActive,
            ),
            itemCounts = mapOf(
                Item.Lamp to 0, Item.MoonPearl to 0, Item.GreenTwenty to 8,
                Item.Flute to 0, Item.ProgressiveGlove to 0, Item.ProgressiveSword to 2,
            ),
            notes = "4/4 fast ganon. start with Boots, Activated Flute, Pearl, Mitts, Master Sword, Lamp",
        )
    },
    CASUAL_BOOTS_FAST(Res.string.gamemode_casual_boots_fast, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.FastGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Standard,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Assured,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            startingEquipment = setOf(Item.PegasusBoots),
            itemCounts = mapOf(Item.GreenTwenty to 1, Item.PegasusBoots to 0),
            notes = "Casual w/ Boots Start",
        )
    },
    OPEN_BOOTS(Res.string.gamemode_open_boots, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            startingEquipment = setOf(Item.PegasusBoots),
            itemCounts = mapOf(Item.GreenTwenty to 1, Item.PegasusBoots to 0),
            notes = "Open w/ Boots Start",
        )
    },
    OPEN_BOOTS_FAST(Res.string.gamemode_open_boots_fast, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.FastGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            startingEquipment = setOf(Item.PegasusBoots),
            itemCounts = mapOf(Item.GreenTwenty to 1, Item.PegasusBoots to 0),
            notes = "Open w/ Boots Start",
        )
    },
    OPEN_FLUTE(Res.string.gamemode_open_flute, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            startingEquipment = setOf(Item.FluteActive),
            itemCounts = mapOf(Item.GreenTwenty to 1, Item.Flute to 0),
            notes = "Open w/ Pre-activated Flute",
        )
    },
    STANDARD_BOOTS(Res.string.gamemode_standard_boots, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Standard,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            startingEquipment = setOf(Item.PegasusBoots),
            itemCounts = mapOf(Item.GreenTwenty to 1, Item.PegasusBoots to 0),
            notes = "Standard w/ Boots Start",
        )
    },

    // --- All Dungeons & Keysanity ---
    ALL_DUNGEONS_BOOTS(Res.string.gamemode_all_dungeons_boots, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.Dungeons,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            startingEquipment = setOf(Item.PegasusBoots),
            itemCounts = mapOf(Item.GreenTwenty to 1, Item.PegasusBoots to 0),
            notes = "All Dungeons Open w/ Boots Start",
        )
    },
    ALL_DUNGEONS_KEYSANITY_BOOTS(Res.string.gamemode_all_dungeons_keysanity_boots, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Full,
            accessibility = Accessibility.Items,
            goal = Goals.Dungeons,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            startingEquipment = setOf(Item.PegasusBoots),
            itemCounts = mapOf(Item.GreenTwenty to 1, Item.PegasusBoots to 0),
            notes = "All Dungeons Keysanity w/ Boots Start",
        )
    },
    CASUAL_ALL_DUNGEONS_BOOTS(Res.string.gamemode_casual_all_dungeons_boots, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.Dungeons,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Standard,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Assured,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            startingEquipment = setOf(Item.PegasusBoots),
            itemCounts = mapOf(Item.GreenTwenty to 1, Item.PegasusBoots to 0),
            notes = "All Dungeons Casual w/ Boots Start",
        )
    },
    FADKEYS(Res.string.gamemode_fadkeys, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Full,
            accessibility = Accessibility.Items,
            goal = Goals.Dungeons,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            allowQuickswap = true,
            itemCounts = mapOf(Item.SmallKeyCT to 0),
            itemPlacements = mapOf(
                ItemLocation.CTDarkMaze to Item.SmallKeyCT,
                ItemLocation.CTFirstFloor to Item.SmallKeyCT,
            ),
            notes = "All Dungeons Keysanity but small keys are in Castle Tower.",
        )
    },
    FADKEYS_GT(Res.string.gamemode_fadkeys_gt, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Full,
            accessibility = Accessibility.Items,
            goal = Goals.Dungeons,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            allowQuickswap = true,
            itemCounts = mapOf(Item.SmallKeyCT to 0, Item.BigKeyGT to 0),
            itemPlacements = mapOf(
                ItemLocation.CTDarkMaze to Item.SmallKeyCT,
                ItemLocation.CTFirstFloor to Item.SmallKeyCT,
                // Static stand-in for sahasrahbot's random-from-~20-GT-locations placement.
                ItemLocation.GTBigKeyChest to Item.BigKeyGT,
            ),
            notes = "AD Keys, but the Castle Tower Keys are in Castle Tower and GT Big Key is in GT.",
        )
    },
    OPEN_BOOTS_MC(Res.string.gamemode_open_boots_mc, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Mc,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            startingEquipment = setOf(Item.PegasusBoots),
            itemCounts = mapOf(Item.GreenTwenty to 1, Item.PegasusBoots to 0),
            notes = "Open w/ Boots Start",
        )
    },
    TOURNAMENT_ALL_DUNGEONS_KEYSANITY_BOOTS(
        Res.string.gamemode_tournament_all_dungeons_keysanity_boots,
        AlttprApi.CUSTOMIZER,
    ) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Full,
            accessibility = Accessibility.Locations,
            goal = Goals.Dungeons,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            startingEquipment = setOf(Item.PegasusBoots),
            itemCounts = mapOf(Item.GreenTwenty to 1, Item.PegasusBoots to 0),
            notes = "All Dungeons Keysanity w/ Boots Start",
        )
    },
    TOURNAMENT_KEYSANITY(Res.string.gamemode_tournament_keysanity, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Full,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            allowQuickswap = true,
            itemCounts = mapOf(Item.SmallKeyCT to 0, Item.BigKeyGT to 0),
            itemPlacements = mapOf(
                ItemLocation.CTDarkMaze to Item.SmallKeyCT,
                ItemLocation.CTFirstFloor to Item.SmallKeyCT,
                // Static stand-in for sahasrahbot's random-from-~20-GT-locations placement.
                ItemLocation.GTBigKeyChest to Item.BigKeyGT,
            ),
            bootsLocationSpoiler = true,
            notes = "Tournament keysanity",
        )
    },

    // --- Hunts: Triforce & Items ---
    EIGHT_PIECE_HUNT(Res.string.gamemode_eight_piece_hunt, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.TriforceHunt,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            goalRequired = 8,
            genericKeys = true,
            regionToggles = CustomRegionToggles(bossNormalLocation = false, wildKeys = true),
            bootsLocationSpoiler = true,
            itemCounts = mapOf(
                Item.HeartContainer to 13, Item.Bow to 1, Item.SancHeartContainer to 0,
                Item.FluteActive to 1, Item.Flute to 0, Item.PegasusBoots to 0,
                Item.HeartPiece to 0, Item.ProgressiveBow to 0, Item.ProgressiveSword to 3,
                Item.SilverArrows to 1, Item.TwentyRupees to 48,
            ),
            itemPlacements = mapOf(
                ItemLocation.Sahasrahla to Item.PegasusBoots,
                ItemLocation.DPBoss to Item.TriforcePiece,
                ItemLocation.EPBoss to Item.TriforcePiece,
                ItemLocation.IPBoss to Item.TriforcePiece,
                ItemLocation.MMBoss to Item.TriforcePiece,
                ItemLocation.SWBoss to Item.TriforcePiece,
                ItemLocation.SPBoss to Item.TriforcePiece,
                ItemLocation.PDBoss to Item.TriforcePiece,
                ItemLocation.THBoss to Item.TriforcePiece,
                ItemLocation.TTBoss to Item.TriforcePiece,
                ItemLocation.TRBoss to Item.TriforcePiece,
            ),
            notes = "Open 8/10 Triforce Hunt. One Piece placed on each dungeon boss. Boots guaranteed on Green Pendant turn-in. Small keys are universal and shuffled in the wild. Flute is Active on pickup. 3 Swords. Rupee Bow is non-progressive. 13 Heart Containers.",
        )
    },
    GOLDRUSH(Res.string.gamemode_goldrush, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Beatable,
            goal = Goals.TriforceHunt,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            goalRequired = 49,
            startingEquipment = setOf(Item.PegasusBoots),
            itemCounts = mapOf(
                Item.HeartPiece to 8, Item.ThreeBombs to 14, Item.TwentyRupees to 12,
                Item.FiftyRupees to 4, Item.TenArrows to 0, Item.PegasusBoots to 0,
                Item.TriforcePiece to 50,
            ),
            notes = "A 49/50 Triforce Hunt, by BigDunka",
        )
    },
    GOLDRUSH_KEYSANITY(Res.string.gamemode_goldrush_keysanity, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Full,
            accessibility = Accessibility.Beatable,
            goal = Goals.TriforceHunt,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            allowQuickswap = true,
            goalRequired = 49,
            startingEquipment = setOf(Item.PegasusBoots),
            itemCounts = mapOf(
                Item.HeartPiece to 8, Item.ThreeBombs to 14, Item.TwentyRupees to 12,
                Item.FiftyRupees to 4, Item.TenArrows to 0, Item.PegasusBoots to 0,
                Item.TriforcePiece to 50,
            ),
            notes = "A 49/50 Triforce Hunt Keysanity, by BigDunka",
        )
    },
    LIGHTSPEED(Res.string.gamemode_lightspeed, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Beatable,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Standard,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            goalRequired = 1,
            prizeToggles = CustomPrizeToggles(crossWorld = false, shuffleCrystals = false),
            // Only the pool-wide tweaks are reproduced here; sahasrahbot's exact guaranteed
            // placement of every dungeon item/pendant/the Triforce itself (~45 pins, including
            // the Triforce fixed at the Pyramid) isn't replicated, so this plays as a normal
            // 1-piece Triforce Hunt rather than the literal "rush the 3 LW dungeons" route.
            itemCounts = mapOf(
                Item.FiveRupees to 5, Item.ProgressiveSword to 1, Item.TwentyRupees to 30,
            ),
            notes = "Complete the 3 Light World pendant dungeons to ascend Agahnim's Tower and grab the Triforce on the Pyramid Ledge.\n\n* 1 progressive sword in the item pool, 1 on the pedestal\n\n* No cape or moon pearl in the item pool\n\n* Pendants shuffled among the Light World",
        )
    },
    TRIFORCE_HUNT_30(Res.string.gamemode_triforce_hunt_30, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.TriforceHunt,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            goalRequired = 30,
            itemCounts = mapOf(Item.TriforcePiece to 40),
            notes = "30/40 Triforce Hunt",
        )
    },
    TRIFORCE_HUNT_40(Res.string.gamemode_triforce_hunt_40, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.TriforceHunt,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            goalRequired = 40,
            itemCounts = mapOf(Item.TriforcePiece to 50),
            notes = "40/50 Triforce Hunt",
        )
    },

    // --- Inverted World ---
    INVROSIA(Res.string.gamemode_invrosia, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Inverted,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Assured,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            allowQuickswap = true,
            regionToggles = CustomRegionToggles(bossNormalLocation = false, wildBigKeys = true),
            bootsLocationSpoiler = true,
            itemCounts = mapOf(Item.BigKeyGT to 0),
            itemPlacements = mapOf(
                // Static stand-in for sahasrahbot's random-from-~20-GT-locations placement.
                ItemLocation.GTBigKeyChest to Item.BigKeyGT,
            ),
            notes = "Ambrosia, but inverted!  Big Keys are shuffled in the wild, except for GT.",
        )
    },
    INVROSIA_BOOTS(Res.string.gamemode_invrosia_boots, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Inverted,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Assured,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            allowQuickswap = true,
            startingEquipment = setOf(Item.PegasusBoots),
            regionToggles = CustomRegionToggles(bossNormalLocation = false, wildBigKeys = true),
            bootsLocationSpoiler = true,
            itemCounts = mapOf(Item.BigKeyGT to 0, Item.PegasusBoots to 0, Item.GreenTwenty to 1),
            itemPlacements = mapOf(
                // Static stand-in for sahasrahbot's random-from-~20-GT-locations placement.
                ItemLocation.GTBigKeyChest to Item.BigKeyGT,
            ),
            notes = "Ambrosia, but inverted!  Big Keys are shuffled in the wild, except for GT.  And you start with boots because Willard wanted it.",
        )
    },
    TOURNAMENT_INVERTED_KEYSANITY(Res.string.gamemode_tournament_inverted_keysanity, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Full,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Inverted,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            allowQuickswap = true,
            startingEquipment = setOf(Item.FluteActive),
            itemCounts = mapOf(Item.FiveRupees to 5, Item.Flute to 0),
        )
    },
    INVERTED_VANILLA(Res.string.gamemode_inverted_vanilla, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.NoLogic,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Beatable,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Inverted,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            regionToggles = CustomRegionToggles(bossNormalLocation = false),
            prizeToggles = CustomPrizeToggles(
                crossWorld = false, shufflePendants = false, shuffleCrystals = false,
            ),
            // sahasrahbot's exact ~200-entry vanilla item placement table isn't reproduced here
            // (it would need a zeroed item pool to match, which is unsafe without every single
            // placement pinned) — this plays as an Inverted/No Logic seed with unshuffled
            // prizes rather than the literal vanilla-placement puzzle.
            notes = "All locations are vanilla, except the world state is inverted.\nYou'll very likely need to use major glitches to beat this.",
        )
    },
    WTFROSIA(Res.string.gamemode_wtfrosia, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Full,
            accessibility = Accessibility.Items,
            goal = Goals.Dungeons,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Inverted,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.Random,
            enemyShuffle = EnemyShuffle.Shuffled,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Assured,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            allowQuickswap = true,
            startingEquipment = setOf(Item.PegasusBoots),
            notes = "AD Keys, Assured Sword, Inverted, Enemizer w/ Boots Start.... because Walther wanted it.",
        )
    },

    // --- Enemizer & Chaos ---
    ENEMIZER_BOOTS(Res.string.gamemode_enemizer_boots, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.Full,
            enemyShuffle = EnemyShuffle.Shuffled,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            startingEquipment = setOf(Item.PegasusBoots),
            itemCounts = mapOf(Item.GreenTwenty to 0, Item.TwentyRupees to 29),
            notes = "Open w/ Boots Start",
        )
    },
    TOURNAMENT_MC_BOSSMIZER(Res.string.gamemode_tournament_mc_bossmizer, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Mc,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.Full,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            allowQuickswap = true,
            startingEquipment = setOf(Item.PegasusBoots),
        )
    },
    BLACK_FRIDAY_HELL_SEED(Res.string.gamemode_black_friday_hell_seed, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Full,
            accessibility = Accessibility.Locations,
            goal = Goals.Dungeons,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Standard,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.Random,
            enemyShuffle = EnemyShuffle.Random,
            potShuffle = Toggle.On,
            hints = Toggle.Off,
            weapons = Weapons.Assured,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            // sahasrahbot's ~28-entry guaranteed placement puzzle (pinning the Ice Rod,
            // Hookshot, Mirror, etc. to specific chests) isn't reproduced — only the boss/enemy
            // chaos and the standalone extra small-key counts (safe without those pins).
            itemCounts = mapOf(
                Item.SmallKeyCT to 1, Item.SmallKeySW to 2, Item.SmallKeyTR to 3,
            ),
        )
    },

    // --- Tournament & League Settings ---
    BOT_TESTING(Res.string.gamemode_bot_testing, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Standard,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Assured,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            allowQuickswap = true,
            startingEquipment = setOf(Item.PegasusBoots),
            itemCounts = mapOf(
                Item.HeartContainer to 2, Item.BottleEmpty to 4, Item.BottleRandom to 0,
                Item.Bow to 1, Item.FiftyRupees to 5, Item.FiveRupees to 7,
                Item.HalfMagic to 0, Item.HeartPiece to 32, Item.ProgressiveBow to 0,
                Item.SilverArrows to 1, Item.SmallMagic to 1,
            ),
            notes = "SG Live 2021 settings\n\nStandard world state w/ starting boots and sword\n\nSee notes at https://gist.github.com/tcprescott/4fe3359cc730ff0aadf490e0105afbec",
        )
    },
    LADDER_S12_OPEN_PSEUDOBOOTS(Res.string.gamemode_ladder_s12_open_pseudoboots, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = true,
            allowQuickswap = true,
            itemCounts = mapOf(
                Item.HeartContainer to 2, Item.BottleEmpty to 4, Item.BottleRandom to 0,
                Item.Bow to 1, Item.FiftyRupees to 5, Item.FiveRupees to 6,
                Item.HalfMagic to 0, Item.HeartPiece to 32, Item.ProgressiveBow to 0,
                Item.SilverArrows to 1, Item.SmallMagic to 1,
            ),
        )
    },
    SGL_GERMANY_OPEN(Res.string.gamemode_sgl_germany_open, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            allowQuickswap = true,
            startingEquipment = setOf(Item.PegasusBoots),
            itemCounts = mapOf(
                Item.HeartContainer to 2, Item.BottleEmpty to 4, Item.BottleRandom to 0,
                Item.FiftyRupees to 5, Item.FiveRupees to 7, Item.HalfMagic to 0,
                Item.HeartPiece to 32, Item.SmallMagic to 1,
            ),
        )
    },
    LADDER_S7_POTPOURRI(Res.string.gamemode_ladder_s7_potpourri, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.Dungeons,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.Full,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            allowQuickswap = true,
            startingEquipment = setOf(Item.Hookshot, Item.IceRod, Item.FluteActive),
            regionToggles = CustomRegionToggles(
                bossNormalLocation = false, wildKeys = true, wildBigKeys = true,
            ),
        )
    },
    SAKU_LEAGUE_BOOTS(Res.string.gamemode_saku_league_boots, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Basic,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.On,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            startingEquipment = setOf(Item.PegasusBoots),
            notes = "Sakuleague w/ Boots Start",
        )
    },
    SPEEDGAMING_LIVE_2022(Res.string.gamemode_speedgaming_live_2022, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            allowQuickswap = true,
            startingEquipment = setOf(Item.PegasusBoots),
            itemCounts = mapOf(
                Item.HeartContainer to 2, Item.BottleEmpty to 4, Item.BottleRandom to 0,
                Item.Bow to 1, Item.FiftyRupees to 5, Item.FiveRupees to 7,
                Item.HalfMagic to 0, Item.HeartPiece to 32, Item.ProgressiveBow to 0,
                Item.SilverArrows to 1, Item.SmallMagic to 1,
            ),
            notes = "SG Live 2022 settings\nOpen world state w/ starting boots\nSee notes at https://gist.github.com/tcprescott/4fe3359cc730ff0aadf490e0105afbec",
        )
    },
    SPEEDGAMING_LIVE_2021(Res.string.gamemode_speedgaming_live_2021, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Standard,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Assured,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            allowQuickswap = true,
            startingEquipment = setOf(Item.PegasusBoots),
            itemCounts = mapOf(
                Item.HeartContainer to 2, Item.BottleEmpty to 4, Item.BottleRandom to 0,
                Item.Bow to 1, Item.FiftyRupees to 5, Item.FiveRupees to 7,
                Item.HalfMagic to 0, Item.HeartPiece to 32, Item.ProgressiveBow to 0,
                Item.SilverArrows to 1, Item.SmallMagic to 1,
            ),
            notes = "SG Live 2021 settings\n\nStandard world state w/ starting boots and sword\n\nSee notes at https://gist.github.com/tcprescott/4fe3359cc730ff0aadf490e0105afbec",
        )
    },
    SPEEDGAMING_LIVE_2023(Res.string.gamemode_speedgaming_live_2023, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Standard,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Assured,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            allowQuickswap = true,
            startingEquipment = setOf(Item.PegasusBoots),
            itemCounts = mapOf(
                Item.HeartContainer to 2, Item.BottleEmpty to 4, Item.BottleRandom to 0,
                Item.FiftyRupees to 5, Item.FiveRupees to 7, Item.HalfMagic to 0,
                Item.HeartPiece to 32, Item.SmallMagic to 1,
            ),
            notes = "Mode breakdown can be found here: https://sglive.speedgaming.org/alttpr-onsite/",
        )
    },
    SPEEDGAMING_LIVE_2024(Res.string.gamemode_speedgaming_live_2024, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            allowQuickswap = true,
            startingEquipment = setOf(Item.PegasusBoots),
            itemCounts = mapOf(
                Item.HeartContainer to 2, Item.BottleEmpty to 4, Item.BottleRandom to 0,
                Item.FiftyRupees to 5, Item.FiveRupees to 7, Item.HalfMagic to 0,
                Item.HeartPiece to 32, Item.SmallMagic to 1,
            ),
            notes = "SG Live 2024 settings. Open world state w/ starting boots. See notes in SGL 2024 Onsite Rules Document",
        )
    },
    TOURNAMENT_HARD_ITEM_POOL(Res.string.gamemode_tournament_hard_item_pool, AlttprApi.CUSTOMIZER) {
        override fun model() = GameModel(
            glitches = Glitches.None,
            itemPlacement = ItemPlacement.Advanced,
            dungeonItems = Keysanity.Standard,
            accessibility = Accessibility.Items,
            goal = Goals.DefeatGanon,
            towerCrystals = Crystals.Seven,
            ganonCrystals = Crystals.Seven,
            worldState = WorldState.Open,
            entrances = Entrances.None,
            bossShuffle = BossShuffle.None,
            enemyShuffle = EnemyShuffle.None,
            potShuffle = Toggle.Off,
            hints = Toggle.Off,
            weapons = Weapons.Randomized,
            itemPool = ItemPool.Normal,
            itemFunctionality = ItemFunctionality.Normal,
            enemyDamage = EnemyDamage.Default,
            enemyHealth = EnemyHealth.Default,
            pseudoboots = false,
            allowQuickswap = true,
            itemCounts = mapOf(
                Item.HeartContainer to 4, Item.BottleEmpty to 4, Item.BottleRandom to 0,
                Item.Bow to 1, Item.FiftyRupees to 5, Item.FiveRupees to 2,
                Item.HalfMagic to 0, Item.OneRupee to 0, Item.HeartPiece to 48,
                Item.ProgressiveArmor to 0, Item.ProgressiveBow to 0, Item.SilverArrows to 1,
                Item.SmallMagic to 1,
            ),
            notes = "48 pieces of heart, 4 heart containers, and 1 sanctuary heart container (max 20 hearts).  Four bottles are placed, 1 is available and will be empty.  No half magic.  No armor.  Three shields placed, capped at Fighter Shield.  Four swords placed, capped at Tempered Sword.  Bows are non-progressive.   Green and blue rupees removed from the pool to account for the extra heart pieces.  Only the sword overflows to a Green 20.",
        )
    };

    abstract fun model(): GameModel
}
