package com.stingers.alttpr.model.api

import alttpr.shared.generated.resources.Res
import alttpr.shared.generated.resources.hash_bow
import alttpr.shared.generated.resources.hash_boomerang
import alttpr.shared.generated.resources.hash_hookshot
import alttpr.shared.generated.resources.hash_bomb
import alttpr.shared.generated.resources.hash_mushroom
import alttpr.shared.generated.resources.hash_powder
import alttpr.shared.generated.resources.hash_ice_rod
import alttpr.shared.generated.resources.hash_pendant
import alttpr.shared.generated.resources.hash_bombos
import alttpr.shared.generated.resources.hash_ether
import alttpr.shared.generated.resources.hash_quake
import alttpr.shared.generated.resources.hash_lantern
import alttpr.shared.generated.resources.hash_hammer
import alttpr.shared.generated.resources.hash_shovel
import alttpr.shared.generated.resources.hash_ocarina
import alttpr.shared.generated.resources.hash_bug_net
import alttpr.shared.generated.resources.hash_book
import alttpr.shared.generated.resources.hash_bottle
import alttpr.shared.generated.resources.hash_green_potion
import alttpr.shared.generated.resources.hash_somaria
import alttpr.shared.generated.resources.hash_cape
import alttpr.shared.generated.resources.hash_mirror
import alttpr.shared.generated.resources.hash_boots
import alttpr.shared.generated.resources.hash_glove
import alttpr.shared.generated.resources.hash_flippers
import alttpr.shared.generated.resources.hash_moon_pearl
import alttpr.shared.generated.resources.hash_shield
import alttpr.shared.generated.resources.hash_mail
import alttpr.shared.generated.resources.hash_heart
import alttpr.shared.generated.resources.hash_map
import alttpr.shared.generated.resources.hash_compass
import alttpr.shared.generated.resources.hash_big_key
import alttpr.shared.generated.resources.hash_flute
import org.jetbrains.compose.resources.DrawableResource
import org.jetbrains.compose.resources.StringResource

enum class Hash(val title: StringResource, val icon: DrawableResource) {
    Bow(Res.string.hash_bow, Res.drawable.hash_bow),
    Boomerang(Res.string.hash_boomerang, Res.drawable.hash_boomerang),
    Hookshot(Res.string.hash_hookshot, Res.drawable.hash_hookshot),
    Bomb(Res.string.hash_bomb, Res.drawable.hash_bomb),
    Mushroom(Res.string.hash_mushroom, Res.drawable.hash_mushroom),
    Powder(Res.string.hash_powder, Res.drawable.hash_powder),
    IceRod(Res.string.hash_ice_rod, Res.drawable.hash_ice_rod),
    Pendant(Res.string.hash_pendant, Res.drawable.hash_pendant),
    Bombos(Res.string.hash_bombos, Res.drawable.hash_bombos),
    Ether(Res.string.hash_ether, Res.drawable.hash_ether),
    Quake(Res.string.hash_quake, Res.drawable.hash_quake),
    Lantern(Res.string.hash_lantern, Res.drawable.hash_lantern),
    Hammer(Res.string.hash_hammer, Res.drawable.hash_hammer),
    Shovel(Res.string.hash_shovel, Res.drawable.hash_shovel),
    Ocarina(Res.string.hash_ocarina, Res.drawable.hash_flute),
    BugNet(Res.string.hash_bug_net, Res.drawable.hash_bug_net),
    Book(Res.string.hash_book, Res.drawable.hash_book),
    Bottle(Res.string.hash_bottle, Res.drawable.hash_bottle),
    GreenPotion(Res.string.hash_green_potion, Res.drawable.hash_green_potion),
    Somaria(Res.string.hash_somaria, Res.drawable.hash_somaria),
    Cape(Res.string.hash_cape, Res.drawable.hash_cape),
    Mirror(Res.string.hash_mirror, Res.drawable.hash_mirror),
    Boots(Res.string.hash_boots, Res.drawable.hash_boots),
    Glove(Res.string.hash_glove, Res.drawable.hash_glove),
    Flippers(Res.string.hash_flippers, Res.drawable.hash_flippers),
    MoonPearl(Res.string.hash_moon_pearl, Res.drawable.hash_moon_pearl),
    Shield(Res.string.hash_shield, Res.drawable.hash_shield),
    Mail(Res.string.hash_mail, Res.drawable.hash_mail),
    Heart(Res.string.hash_heart, Res.drawable.hash_heart),
    Map(Res.string.hash_map, Res.drawable.hash_map),
    Compass(Res.string.hash_compass, Res.drawable.hash_compass),
    BigKey(Res.string.hash_big_key, Res.drawable.hash_big_key),
}
